export const brandConfig = {
  businessName: "Sanro Doors",
  legalName: "Sanro Fibre Glass Industries",
  tagline: "Designed to open possibilities",
  logo: "/logo.png",
  primaryColor: "#003f34",
  secondaryColor: "#8B5A3C",
  highlightColor: "#B2FFD6",
  address: "Thankamany – Thopramkudy Road, Idukki, Kerala 685609",
  phone: "04862 123 456",
  email: "accounts@sanrodoors.in",
  gstin: "32AABCS1234A1Z5",
  githubRepo: "realcaps04/Sanro-Fibre-Glass-Industries",
  githubBranch: "main",
} as const;
